"""
Introductory demo — Intent → Infrastructure (Scenario 1).

This is a self-contained walkthrough of the AgenticDevops pipeline:
  1. Natural language intent
  2. IntentSpec construction with confidence bands
  3. OPA security gate check
  4. Terraform generation
  5. CI/CD pipeline generation
  6. Validation summary

Run:
    python examples/demo_intro.py

No external services required — all output is illustrative.
Full source: github.com/dmiruke-ai/AgenticDevops (private).
"""

import asyncio
from uuid import uuid4

from intent_spec import (
    ConfidenceBand,
    IntentCategory,
    IntentSpec,
    SpecItem,
)


# ---------------------------------------------------------------------------
# Display helpers
# ---------------------------------------------------------------------------

def step(n: int, title: str) -> None:
    print(f"\n  ┌─ Step {n}: {title}")
    print("  │")


def out(text: str, indent: int = 4) -> None:
    for line in text.splitlines():
        print(f"  │{' ' * indent}{line}")


def end_step() -> None:
    print(f"  └{'─' * 68}")


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------

async def run() -> None:
    # ── Step 1: raw user intent ──────────────────────────────────────────
    step(1, "User Intent (natural language)")
    user_message = (
        "Deploy a scalable web application on AWS with EKS, "
        "auto-scaling, and a CI/CD pipeline using GitHub Actions"
    )
    out(f'"{user_message}"')
    end_step()

    # ── Step 2: IntentSpec construction ──────────────────────────────────
    step(2, "Intent Parsing → IntentSpec")

    spec = IntentSpec(session_id=f"demo-{str(uuid4())[:8]}")

    extracted = [
        ("cloud_provider",  "AWS",            ConfidenceBand.STATED,    IntentCategory.TASK,       "User said 'AWS'"),
        ("compute_platform","EKS",            ConfidenceBand.STATED,    IntentCategory.TASK,       "User said 'EKS'"),
        ("scaling",         "auto-scaling",   ConfidenceBand.STATED,    IntentCategory.TASK,       "User said 'auto-scaling'"),
        ("ci_cd_platform",  "GitHub Actions", ConfidenceBand.STATED,    IntentCategory.TASK,       "User said 'GitHub Actions'"),
        ("region",          "us-east-1",      ConfidenceBand.INFERRED,  IntentCategory.CONSTRAINT, "Default; user did not specify"),
        ("node_count",      "3",              ConfidenceBand.INFERRED,  IntentCategory.CONSTRAINT, "Standard HA minimum"),
    ]

    icons = {
        ConfidenceBand.STATED:      "●",
        ConfidenceBand.CONFIRMED:   "◉",
        ConfidenceBand.INFERRED:    "○",
        ConfidenceBand.SPECULATIVE: "◌",
    }

    for key, value, confidence, category, evidence in extracted:
        item = SpecItem(key=key, value=value, confidence=confidence,
                        category=category, evidence=evidence, turn=1)
        spec.items[item.id] = item

    out(f"session_id : {spec.session_id}")
    out(f"version    : {spec.version}")
    out(f"items      : {len(spec.items)}")
    out("")
    out("Extracted items:")
    for item in spec.items.values():
        out(f"  {icons[item.confidence]} {item.key}: {item.value}  [{item.confidence.value}]")
    end_step()

    # ── Step 3: OPA security gate ─────────────────────────────────────────
    step(3, "OPA Security Gate")
    out("  ✓ No wildcard IAM  (Resource: \"*\")")
    out("  ✓ No open security groups  (0.0.0.0/0 on sensitive ports)")
    out("  ✓ No prompt-injection patterns  (15 checks)")
    out("  ✓ Intent structure valid")
    out("")
    out("Result: ALLOWED → proceed to generation")
    end_step()

    # ── Step 4: Terraform generation ─────────────────────────────────────
    step(4, "Terraform Generation")
    terraform = f"""\
# Generated by AgenticDevops · session {spec.session_id}

terraform {{
  required_version = ">= 1.0"
  required_providers {{
    aws = {{ source = "hashicorp/aws", version = "~> 5.0" }}
  }}
}}

provider "aws" {{ region = "us-east-1" }}

module "eks" {{
  source          = "terraform-aws-modules/eks/aws"
  version         = "~> 19.0"
  cluster_name    = "demo-cluster"
  cluster_version = "1.28"
  vpc_id          = module.vpc.vpc_id
  subnet_ids      = module.vpc.private_subnets

  eks_managed_node_groups = {{
    default = {{
      min_size     = 2
      max_size     = 10
      desired_size = 3
      instance_types = ["t3.medium"]
    }}
  }}
}}"""
    out("Generated: main.tf")
    out("─" * 48)
    out(terraform)
    end_step()

    # ── Step 5: CI/CD generation ─────────────────────────────────────────
    step(5, "CI/CD Pipeline Generation")
    cicd = """\
# Generated by AgenticDevops
name: Deploy to EKS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name demo-cluster
          kubectl apply -f k8s/"""
    out("Generated: .github/workflows/deploy.yml")
    out("─" * 48)
    out(cicd)
    end_step()

    # ── Step 6: validation summary ────────────────────────────────────────
    step(6, "Validation")
    out("  ✓ terraform validate  — configuration is valid")
    out("  ✓ terraform plan      — 12 to add · 0 to change · 0 to destroy")
    end_step()

    # ── Summary ───────────────────────────────────────────────────────────
    print()
    print("  ╔══════════════════════════════════════════════════════════════╗")
    print("  ║  COMPLETE                                                    ║")
    print("  ║  Input : natural language intent                             ║")
    print("  ║  Output: validated Terraform + GitHub Actions pipeline       ║")
    print("  ║                                                              ║")
    print("  ║  Artifacts: main.tf · vpc.tf · .github/workflows/deploy.yml ║")
    print("  ╚══════════════════════════════════════════════════════════════╝")


if __name__ == "__main__":
    asyncio.run(run())
